version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    command: >
      sh -c "poetry run python manage.py runserver 0.0.0.0:8000"
