name: Quality Assurance

on:
  strategy:
      fail-fast: false
      matrix:
        poetry-version: ["1.2.2", "1.7.1"]
  push:
    branches: [ "main" ]

jobs:
  qulity-assurance:
    name: Qulity Assurance
    runs-on: ubuntu-latest
    container: FROM python:3.10-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Run image
          uses: abatilo/actions-poetry@v2
          with:
            poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test