name: Quality Assurance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  


jobs:
  qulity-assurance:
    name: Qulity Assurance
    runs-on: ubuntu-latest
    container: python:3.10-alpine
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v4

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test